#:schema node_modules/wrangler/config-schema.json
name = "sublink-transform"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "2db40219f1724bab82ecf30c125a4a76" }
]

[assets]
directory = "./public"
